package com.github.st1hy.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.github.st1hy.dao.OpenedImage;

import com.github.st1hy.dao.OpenedImageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig openedImageDaoConfig;

    private final OpenedImageDao openedImageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        openedImageDaoConfig = daoConfigMap.get(OpenedImageDao.class).clone();
        openedImageDaoConfig.initIdentityScope(type);

        openedImageDao = new OpenedImageDao(openedImageDaoConfig, this);

        registerDao(OpenedImage.class, openedImageDao);
    }
    
    public void clear() {
        openedImageDaoConfig.getIdentityScope().clear();
    }

    public OpenedImageDao getOpenedImageDao() {
        return openedImageDao;
    }

}
